spring:
  datasource:
    username: root
    password: wuguipeng
    url: jdbc:mysql://cloud.kunpeng.gq:3306/mall_ums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: cloud.kunpeng.gq:8848
  application:
    name: mall-member

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 8000