spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: http://127.0.0.1:10001
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        - id: member_route
          uri: http://127.0.0.1:8000
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        - id: third_party_route
          uri: http://127.0.0.1:30000
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*), /$\{segment}

        - id: admin_route
          uri: http://cloud.xyxdbp.xyz:8080
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}




